import { NextResponse } from 'next/server';
import { readCollection, mutateCollection } from '@/lib/server-db';
import { dispatchCommitteeRosterEmails } from '@/lib/committee-roster-email';
import { fanOutAutoApproval, resolveCustomApprovalPanel } from '@/lib/approval-sync';
import { requireSession } from '@/lib/session';
import { apiError } from '@/lib/api-error';
import { gateEventAction, holdEditForApproval, stampPendingCreate, changedKeys, isPendingState } from '@/lib/approval-gate';

const PENDING_APPROVAL_MESSAGE: Record<string, string> = {
  pending_create: 'This event was created and needs sign-off from the Centre Head, Advisor, or GG Campus Events Head before it goes live.',
  pending_edit: 'An edit to this event needs sign-off from the Centre Head, Advisor, or GG Campus Events Head.',
  pending_delete: 'A request to delete this event needs sign-off from the Centre Head, Advisor, or GG Campus Events Head.',
};

const COMMITTEE_PENDING_MESSAGE: Record<string, string> = {
  pending_create: 'A new event committee was created and needs sign-off from the Centre Head, Advisor, or GG Campus Events Head.',
  pending_members: 'A committee roster update needs sign-off from the Centre Head, Advisor, or GG Campus Events Head.',
};

// Committee approval fan-out (see /api/events/[id]'s PATCH handler) only
// fires on the PATCH transition into a pending state, so any committee that
// was already pending before that wiring existed never got its ApprovalRequest
// rows created. Back-fill those once per server process — safe to run
// repeatedly since fanOutAutoApproval is itself idempotent (a no-op once a
// pending autoGenerated row already exists for the entity).
let committeeApprovalBackfillDone = false;
async function backfillPendingCommitteeApprovals(events: any[]) {
  if (committeeApprovalBackfillDone) return;
  committeeApprovalBackfillDone = true;
  for (const event of events) {
    for (const committee of event.committees || []) {
      if (committee.approvalStatus !== 'pending_create' && committee.approvalStatus !== 'pending_members') continue;
      try {
        await fanOutAutoApproval({
          entityType: 'committee',
          entityId: committee.id,
          entityTitle: committee.name,
          eventId: event.id,
          requesterId: committee.submittedBy || '',
          requesterName: committee.submittedBy || 'A member',
          requesterEmail: committee.submittedByEmail,
          message: COMMITTEE_PENDING_MESSAGE[committee.approvalStatus],
        });
      } catch (approvalErr) {
        console.error('[events-api] Committee approval back-fill failed:', approvalErr);
      }
    }
  }
}

export async function GET(request: Request) {
  try {
    await requireSession(request);
    const items = await readCollection('events');
    await backfillPendingCommitteeApprovals(items as any[]);
    return NextResponse.json(items);
  } catch (err: any) {
    return apiError(err, 'events-api-get', 500);
  }
}

export async function POST(request: Request) {
  try {
    // Route already branches into a pending-approval path (approvalStatus /
    // approverType computed by the client) when the actor isn't fully
    // trusted — see the fan-out block below — so the gate here is just
    // "must be a real signed-in member," not a hard canCreateEvent check.
    const actor = await requireSession(request);
    const item = await request.json();
    // Chain of command: whether this creation needs sign-off is decided HERE from the stored Group Policies — not from
    // the approvalStatus the browser chose to send (a stale policy cache used to let creations go straight through).
    const stored = (await readCollection<any>('events')).find((e: any) => e.id === item.id);
    if (!stored) {
      // never trust an approvalStatus the browser put on a NEW record ("approved" would skip sign-off entirely)
      const gate = await gateEventAction(actor, 'CREATE');
      if (!gate.allowed) {
        return NextResponse.json({ error: "You don't have permission to create events." }, { status: 403 });
      }
      if (gate.requiresApproval) stampPendingCreate(item, gate, actor);
    } else {
      // POST with an existing id replaces the record. It can neither decide a pending item (that is PATCH + approver
      // check) nor dodge the edit gate, so approval bookkeeping is taken from the stored record and any content change
      // is run through the same edit gate as PATCH.
      const bookkeeping = ['approvalStatus', 'pendingChange', 'submittedBy', 'submittedByEmail', 'approverType', 'approverMemberId', 'approverPolicyTagId', 'approvalPolicyName', 'approverName', 'decidedBy', 'decidedAt', 'rejectionReason'];
      const ignore = new Set([...bookkeeping, 'committees']);
      const keys = changedKeys(stored, item, ignore);
      for (const k of bookkeeping) { if (k in stored) item[k] = stored[k]; else delete item[k]; }
      if (keys.length > 0 && !isPendingState(stored.approvalStatus)) {
        const gate = await gateEventAction(actor, 'EDIT');
        if (!gate.allowed) return NextResponse.json({ error: "You don't have permission to edit events." }, { status: 403 });
        if (gate.requiresApproval) {
          const upd: Record<string, any> = {};
          for (const k of keys) upd[k] = item[k];
          holdEditForApproval(stored, upd, keys, gate, actor);
          const base = { ...stored };
          for (const k of Object.keys(item)) delete item[k];
          Object.assign(item, base, upd);
        }
      }
    }
    let previous: any = null;
    const updated = await mutateCollection('events', (current) => {
      const idx = current.findIndex((e: any) => e.id === item.id);
      if (idx >= 0) {
        previous = current[idx];
        const copy = [...current];
        copy[idx] = item;
        return copy;
      }
      return [item, ...current];
    });
    const created = updated.find((e: any) => e.id === item.id);

    // Route the built-in Group Policy approval gate (approvalStatus/
    // approverType — see EventItem's doc comment in local-data.ts) into the
    // Approvals module too, so festivals and every other event this fires
    // for actually shows up there. A SPECIFIC_MEMBER/POLICY_TAG approver is
    // resolved to its own custom panel instead of the default trio, so a
    // named approver actually gets notified and tracked.
    if (
      created &&
      (created.approvalStatus === 'pending_create' || created.approvalStatus === 'pending_edit' || created.approvalStatus === 'pending_delete')
    ) {
      try {
        const customPanel = created.approverType && created.approverType !== 'CENTER_HEAD'
          ? await resolveCustomApprovalPanel(created.approverType, created.approverMemberId, created.approverPolicyTagId)
          : undefined;
        await fanOutAutoApproval({
          entityType: 'event',
          entityId: created.id,
          entityTitle: created.title,
          requesterId: created.submittedBy || '',
          requesterName: created.submittedBy || 'A member',
          requesterEmail: created.submittedByEmail,
          message: PENDING_APPROVAL_MESSAGE[created.approvalStatus],
          customPanel,
        });
      } catch (approvalErr) {
        console.error('[events-api] Approval fan-out failed:', approvalErr);
      }
    }

    // Automated email to newly appointed committee members (diffed against the
    // previous record so an upsert doesn't re-email existing members).
    if (created) {
      try {
        await dispatchCommitteeRosterEmails(previous, created);
      } catch (emailErr) {
        console.error('[events-api] Email dispatch failed:', emailErr);
      }
    }

    return NextResponse.json(created, { status: 201 });
  } catch (err: any) {
    return apiError(err, 'events-api-post', 400);
  }
}
