/**
 * report-generator.ts — Builds a real, downloadable PDF report from a fixed
 * template, entirely client-side (jsPDF + jspdf-autotable). Replaces the old
 * "Print Report" button, which just called window.print() on the live
 * dashboard page — inheriting the app chrome, on-screen chart tooltips, and
 * whatever theme happened to be active, with no real document structure.
 *
 * No server round-trip and no headless-browser dependency (Puppeteer/
 * Playwright) — this runs in the visitor's browser and triggers a native
 * file download, which keeps the self-hosted VPS deployment light.
 */
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { RatingItem } from './local-data';

const BRAND_PRIMARY: [number, number, number] = [15, 42, 71]; // #0F2A47
const BRAND_ACCENT: [number, number, number] = [46, 117, 182]; // #2E75B6
const TEXT_DARK: [number, number, number] = [30, 41, 59];
const TEXT_MUTED: [number, number, number] = [100, 116, 139];
const BORDER_LIGHT: [number, number, number] = [226, 232, 240];

function scoreBand(score: number): string {
  if (score >= 4.5) return 'Excellent';
  if (score >= 3.5) return 'Good';
  if (score >= 2.5) return 'Satisfactory';
  if (score >= 1.5) return 'Needs Improvement';
  return 'Unsatisfactory';
}

export interface PerformanceReportParams {
  ratings: RatingItem[];
  averages: { quality: number; timeliness: number; initiative: number; collaboration: number; overall: number };
  scope: { division: string; member: string; quarter: string };
  generatedBy: string;
}

export function generatePerformanceReportPdf(params: PerformanceReportParams): void {
  const { ratings, averages, scope, generatedBy } = params;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  let y = 0;

  // ---- Letterhead ----
  doc.setFillColor(...BRAND_PRIMARY);
  doc.rect(0, 0, pageWidth, 90, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('LEADS Next Gen Centre', margin, 38);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text('Task Performance Evaluation Report', margin, 58);
  doc.setFontSize(8.5);
  doc.setTextColor(200, 215, 230);
  doc.text('MSRUAS Portal — Confidential, Internal Use Only', margin, 74);
  y = 112;

  // ---- Metadata block ----
  doc.setTextColor(...TEXT_MUTED);
  doc.setFontSize(9);
  const generatedAt = new Date().toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' });
  const metaLines = [
    `Generated: ${generatedAt}`,
    `Generated by: ${generatedBy}`,
    `Scope: Division = ${scope.division} · Member = ${scope.member} · Quarter = ${scope.quarter}`,
    `Total Evaluations in Scope: ${ratings.length}`,
  ];
  metaLines.forEach((line, i) => doc.text(line, margin, y + i * 13));
  y += metaLines.length * 13 + 18;

  // ---- Executive summary ----
  doc.setTextColor(...TEXT_DARK);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Executive Summary', margin, y);
  y += 10;

  const summaryRows = [
    ['Quality', averages.quality, scoreBand(averages.quality)],
    ['Timeliness', averages.timeliness, scoreBand(averages.timeliness)],
    ['Initiative', averages.initiative, scoreBand(averages.initiative)],
    ['Collaboration', averages.collaboration, scoreBand(averages.collaboration)],
    ['Overall Average', averages.overall, scoreBand(averages.overall)],
  ];

  autoTable(doc, {
    startY: y + 8,
    margin: { left: margin, right: margin },
    head: [['Metric', 'Average Score (/5.0)', 'Band']],
    body: summaryRows.map(([label, score, band]) => [label, `${score} / 5.0`, band]),
    theme: 'grid',
    headStyles: { fillColor: BRAND_ACCENT, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 9, textColor: TEXT_DARK },
    alternateRowStyles: { fillColor: [246, 249, 252] },
    didParseCell: (data) => {
      if (data.section === 'body' && data.row.index === summaryRows.length - 1) {
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  // ---- Score distribution ----
  const bands = ['Excellent', 'Good', 'Satisfactory', 'Needs Improvement', 'Unsatisfactory'];
  const distribution = bands.map(band => ({
    band,
    count: ratings.filter(r => scoreBand(r.overallScore) === band).length,
  }));

  const afterSummaryY = (doc as any).lastAutoTable.finalY + 22;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...TEXT_DARK);
  doc.text('Score Distribution', margin, afterSummaryY);

  autoTable(doc, {
    startY: afterSummaryY + 8,
    margin: { left: margin, right: margin },
    head: [['Performance Band', 'Evaluations', 'Share']],
    body: distribution.map(d => [
      d.band,
      String(d.count),
      ratings.length > 0 ? `${((d.count / ratings.length) * 100).toFixed(0)}%` : '0%',
    ]),
    theme: 'grid',
    headStyles: { fillColor: BRAND_PRIMARY, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 9, textColor: TEXT_DARK },
    alternateRowStyles: { fillColor: [246, 249, 252] },
  });

  // ---- Detailed audit log (new page for a clean start) ----
  doc.addPage();
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...TEXT_DARK);
  doc.text('Audited Performance Logs', margin, 40);

  autoTable(doc, {
    startY: 52,
    margin: { left: margin, right: margin },
    head: [['Student', 'Task', 'Event', 'Evaluator', 'Quarter', 'Qual.', 'Time.', 'Init.', 'Collab.', 'Overall', 'Date', 'Remarks']],
    body: ratings.map(r => [
      r.targetName,
      r.taskTitle,
      r.eventName || '—',
      r.raterName,
      r.quarter || '2026-Q3',
      r.quality.toFixed(1),
      r.timeliness.toFixed(1),
      r.initiative.toFixed(1),
      r.collaboration.toFixed(1),
      r.overallScore.toFixed(1),
      (r.createdAt || '').split('T')[0],
      r.notes || '—',
    ]),
    theme: 'striped',
    styles: { fontSize: 7.5, cellPadding: 4, textColor: TEXT_DARK, lineColor: BORDER_LIGHT },
    headStyles: { fillColor: BRAND_PRIMARY, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7.5 },
    alternateRowStyles: { fillColor: [246, 249, 252] },
    columnStyles: {
      1: { cellWidth: 70 },
      2: { cellWidth: 55 },
      11: { cellWidth: 80 },
    },
  });

  // ---- Footer on every page ----
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setDrawColor(...BORDER_LIGHT);
    doc.line(margin, pageHeight - 34, pageWidth - margin, pageHeight - 34);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.text('LEADS Next Gen Centre — Confidential', margin, pageHeight - 20);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 20, { align: 'right' });
  }

  const stamp = new Date().toISOString().split('T')[0];
  doc.save(`leads_performance_report_${stamp}.pdf`);
}
